apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo= # base64 encoded 'root'. Use `echo 'root' | base64` to encode your own password
